"""Clear local listening gate: three primary audio tests, optional video, honest joins."""
import json,wave,html
from pathlib import Path
import numpy as np
R=Path(__file__).resolve().parents[1];O=R/'results/dense'
def load(p):
 with wave.open(str(p)) as f:sr=f.getframerate();a=np.frombuffer(f.readframes(f.getnframes()),'<i2').reshape(-1,f.getnchannels())/32768
 return a,sr
def data(name,title,description):
 p=O/name
 if not (p/'summary.json').exists():return None
 a,sr=load(p/'heard.wav');dur=len(a)/sr;n=sr//10;e=np.sqrt(np.mean(a[:len(a)//n*n].reshape(-1,n,2)**2,axis=(1,2)))
 bs=[json.loads(t) for t in (p/'boundaries.jsonl').read_text().splitlines()];blocks=[json.loads(t) for t in (p/'audio_blocks.jsonl').read_text().splitlines()];rows=[json.loads(t) for t in (p/'trace.jsonl').read_text().splitlines()];jobs=[json.loads(t) for t in (p/'jobs.jsonl').read_text().splitlines()];summary=json.loads((p/'summary.json').read_text())
 ending=json.loads((p/'ending.json').read_text()) if (p/'ending.json').exists() else None
 limit=ending['audio_frame']/sr if ending else dur
 joins=[b['new_material_audio_s'] for b in bs if b['new_material_audio_s']<limit];anchors=[[max(0,t-44*4096/44100),t] for t in joins[1:]]
 # The final anchor can be heard even when its following new-material boundary is past EOF.
 if joins and joins[-1]+26.0063541667-44*4096/44100<limit:anchors.append([joins[-1]+26.0063541667-44*4096/44100,min(limit,joins[-1]+26.0063541667)])
 stages=[]
 for j in jobs:
  if j['play_at_audio_s']<limit:stages.append({'t':j['play_at_audio_s'],'label':'SA3 intent: '+j.get('trajectory',j['conditioning'])})
 events=[]
 if name=='live_curve':
  first=next(b for b in blocks if b['phase']=='anticipation' and b['amount']>0);active=next(r for r in rows if r['activation'] is not None);event=next(r for r in rows if r['phase']=='event')
  events=[{'t':first['audio_s'],'label':'Musical response starts'}, {'t':141.531554781-(blocks[0]['callback_wall']-blocks[0]['replay_origin_wall']),'label':'Offline sustained steering onset'}, {'t':event['predicted_peak']-(blocks[0]['callback_wall']-blocks[0]['replay_origin_wall']),'label':'Model-predicted peak (not measured apex)'}]
  description+=' The onset/apex references are evaluation-only; they are not runtime triggers. No measured physical apex is claimed.'
 if ending:
  trigger=ending.get('trigger_audio_frame',ending['audio_frame'])/sr;entry=ending['audio_frame']/sr
  closing=[j for j in jobs if j['conditioning']=='closing']
  for j in closing[:1]:
   # Request time maps to the captured callback clock, not an assumed route start.
   nearest=min(blocks,key=lambda b:abs(b['route_t']-j['route_t']));events.append({'t':nearest['audio_s'],'label':'Closing requested from available nav'})
   if j['play_at_audio_s']<entry:events.append({'t':j['play_at_audio_s'],'label':'Generated closing reaches playback'})
  events += [{'t':trigger,'label':'Causal arrival trigger'},{'t':entry,'label':'Cadence enters after %.3f s runway'%ending.get('actual_runway_seconds',0)},{'t':entry+5,'label':'Cadence complete / silence'}]
  description+=' The final sonority is unchanged; only its entry is selected from already-generated music. Pulse alignment is approximate, not bar detection.'
 times=[j['seconds'] for j in summary['generation']];perf={'duration':dur,'accepted_jobs':len(times),'median_generation':float(np.median(times)) if times else None,'min_generation':min(times) if times else None,'max_generation':max(times) if times else None,'playback_rtf':float(np.median([j['seconds']/j['usable_new_seconds'] for j in summary['generation']])) if times else None,'fallbacks':summary['fallbacks'],'flags':summary['underflows']}
 return {'name':name,'title':title,'description':description,'file':name+'/heard.wav','duration':dur,'db':(20*np.log10(np.maximum(e,1e-8))).tolist(),'joins':joins,'anchors':anchors,'stages':stages,'events':events,'performance':perf}
primary=[x for x in [data('live_development','1. DENSE LIVE CONTINUITY — 210-second performance','Horizon Drive with explicit arrangement-stage conditioning and the same active-context/anchor continuation architecture. Listen for a continuous groove, recurring identity and changing instrumental density. No offline gap repairs or time stretching. Listen particularly around recurring-anchor entries near 43.84, 95.85 and 199.88 seconds: pulse diagnostics flagged possible shifts there, but cannot establish their musical audibility.'),data('live_curve','2. LIVE CURVE — energetic Horizon','Live model-derived timing with short eighth/sixteenth-note reprises of transient bands extracted from the current generated music. Strength scales with predicted curve severity; the event accent and release are deterministic. No prerecorded percussion or universal drop.'),data('live_arrival','3. LIVE ARRIVAL — phrase-aware closing','Generated closing music leads into the previously liked deterministic cadence. A bounded 0.8–3.5-second runway selects a pulse/release opportunity after the unchanged causal arrival trigger.')] if x]
diag=[x for x in [data('stress_baseline','Controlled dense stress test — original response','Same dense identity, prior prompt blending and original Conductor. Preserved before arrangement and cadence changes.')] if x]
styles='''body{font:17px system-ui;background:#111821;color:#edf1f6;max-width:1100px;margin:32px auto;padding:0 20px}section{border-top:1px solid #40516a;padding:25px 0}audio{width:100%}canvas{width:100%;height:150px;background:#192431}a{color:#9ee7df}small{color:#bbc8d6}p{line-height:1.5}button{background:#293c50;color:#edf1f6;border:1px solid #607992;padding:6px;margin:3px;border-radius:4px}.stats{color:#a8e6c4}.events{line-height:1.8}h2{font-size:23px}summary{cursor:pointer;padding:12px}'''
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>RoadScore — Make the music move</title><style>__STYLE__</style><h1>RoadScore: Horizon Drive</h1><p><b>Three primary audio tests below.</b> Start with the music; timing and generation markers are optional. No audio starts automatically. These are actual live-rendered captures; human musical acceptance is pending.</p><p>The unchanged continuation method adds 21.920 seconds of newly generated music plus a disclosed 4.087-second recurring anchor per job. Orange lines mark new-material boundaries; purple bands mark reused anchors. No post-hoc silence removal, gain repair, time stretching or route-specific soundtrack editing.</p><main id="primary"></main><section><h2>OPTIONAL VIDEO REVIEW LINKS</h2><p><a href="curve_review.html">Synchronized curve video</a> · <a href="arrival_review.html">Synchronized arrival video</a></p><small>These are separate video reviews, not substitutes for the three primary audio tests above. Timestamp alignment uses recorded camera timing plus measured callback/DAC delay. Bench output stayed muted.</small></section><details><summary>Controlled stress test, seeds and diagnostics</summary><div id="diagnostics"></div><h3>Same-source curve A/B (diagnostic re-render, not a live take)</h3><p>Existing phrase echoes, same pulse estimate and captured causal state</p><audio controls preload="metadata" src="curve_same_source_old.wav"></audio><p>Added Horizon Drive transient reprises</p><audio controls preload="metadata" src="curve_same_source_reprises.wav"></audio><p>Two fresh seeds of one dense prompt; no broad model/style search. These are prompt candidates, not verified instrument labels.</p><p>Seed 7301 (selected)</p><audio controls preload="metadata" src="dense_seed_0.wav"></audio><p>Seed 7302</p><audio controls preload="metadata" src="dense_seed_1.wav"></audio><p><a href="boundary_metrics.json">Every-join pulse/transient diagnostics</a> · <a href="live_metrics.json">Live runtime measurements</a> · <a href="seed_metrics.json">Sparse/dense source comparison</a> · <a href="../continuity/listen.html">Prior provisionally accepted sparse Horizon</a></p><p>Pulse estimates and spectral/transient counts do not establish musical success or identify individual instruments. Reused anchors can still be recognizable; evaluate every join by ear.</p></details><script>
const PRIMARY=__PRIMARY__,DIAGNOSTICS=__DIAG__;
function render(p,target){const s=document.createElement('section');const title=document.createElement('h2');title.textContent=p.title;s.append(title);const desc=document.createElement('p');desc.textContent=p.description;s.append(desc);const a=document.createElement('audio');a.controls=true;a.preload='metadata';a.src=p.file;s.append(a);const stat=document.createElement('p');stat.className='stats';const m=p.performance;stat.textContent=`${m.duration.toFixed(1)} s · ${m.accepted_jobs} accepted live jobs · median ${m.median_generation?.toFixed(2)} s/job · ${m.playback_rtf?.toFixed(3)} playback RTF · ${m.fallbacks} fallbacks · ${m.flags} output flags`;s.append(stat);const detail=document.createElement('details');detail.innerHTML='<summary>Show boundaries, musical intent and event timing</summary>';const c=document.createElement('canvas');c.width=1100;c.height=150;detail.append(c);const legend=document.createElement('p');legend.className='events';detail.append(legend);const markers=[...p.joins.map(t=>({t,label:'Generation boundary'})),...p.anchors.map(([t])=>({t,label:'Recurring anchor enters'})),...p.events,...p.stages].sort((a,b)=>a.t-b.t);for(const mark of markers){const b=document.createElement('button');b.textContent=mark.t.toFixed(3)+' s — '+mark.label;b.onclick=()=>{a.currentTime=Math.max(0,mark.t-3)};legend.append(b)}s.append(detail);document.getElementById(target).append(s);const ctx=c.getContext('2d');function draw(){ctx.clearRect(0,0,1100,150);for(const [lo,hi] of p.anchors){ctx.fillStyle='#9a6be85a';ctx.fillRect(lo/p.duration*1100,0,(hi-lo)/p.duration*1100,150)}for(const db of [-20,-40,-60]){const y=-db/80*140;ctx.strokeStyle='#40516a';ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(1100,y);ctx.stroke();ctx.fillStyle='#b2c4d8';ctx.fillText(db+' dBFS',4,y-3)}ctx.strokeStyle='#7be5c1';ctx.beginPath();p.db.forEach((v,i)=>{const x=i/p.db.length*1100,y=-Math.max(-80,v)/80*140;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();for(const t of p.joins){ctx.strokeStyle='#ffb663';ctx.beginPath();ctx.moveTo(t/p.duration*1100,0);ctx.lineTo(t/p.duration*1100,150);ctx.stroke()}ctx.strokeStyle='white';ctx.beginPath();ctx.moveTo(a.currentTime/p.duration*1100,0);ctx.lineTo(a.currentTime/p.duration*1100,150);ctx.stroke()}c.onclick=e=>{a.currentTime=(e.clientX-c.getBoundingClientRect().left)/c.clientWidth*p.duration};a.ontimeupdate=draw;detail.ontoggle=draw;draw()}
PRIMARY.forEach(p=>render(p,'primary'));DIAGNOSTICS.forEach(p=>render(p,'diagnostics'));
</script></html>'''
(O/'listen.html').write_text(page.replace('__STYLE__',styles).replace('__PRIMARY__',json.dumps(primary)).replace('__DIAG__',json.dumps(diag)))
(O/'review_metadata.json').write_text(json.dumps({'primary':primary,'diagnostics':diag},indent=2))
print('Primary sections:',[x['name'] for x in primary])
