"""One concise, entirely local listening gate. Never autoplay or publish."""
import html,json
from pathlib import Path
R=Path(__file__).resolve().parents[1];O=R/'results/overnight'
def player(path,video=False):
 tag='video' if video else 'audio';poster=' poster="curve_overlay_preparation.png"' if video else '';return f'<{tag} controls preload="none"{poster} src="{html.escape(path)}"></{tag}>'
parts=['''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>RoadScore · Overnight listening gate</title><style>body{font:16px/1.5 system-ui;background:#10151d;color:#e8edf4;max-width:980px;margin:32px auto;padding:0 18px}h1{margin-bottom:8px}h2{margin-top:36px}section{border:1px solid #334353;background:#17202b;border-radius:12px;padding:16px;margin:12px 0}audio,video{width:100%;margin-top:8px}small,p.note{color:#b7c6d6}summary{cursor:pointer}table{border-collapse:collapse;width:100%}td,th{text-align:left;border-bottom:1px solid #345;padding:8px}a{color:#8bd4fa}pre{white-space:pre-wrap;overflow-wrap:anywhere}</style></head><body><h1>RoadScore · Overnight listening gate</h1><p>Breakbeat is the primary direction. All files were rendered and captured with physical output muted. Nothing autoplays.</p><p class="note"><b>Musical acceptance is still yours.</b> Requested roles, spectral differences and precise scheduling do not establish that these sound like one convincing song. Snapshot experiments that failed numerical validation are excluded from the listening choices below.</p>''']
parts.append('<h2>A. Breakbeat section identity</h2><p>These are the validated chained-context candidates. Listen for a recognizable identity, a substantially larger chorus, and a coherent contrasting bridge.</p>')
for role,name in [('Verse','0_verse'),('Prechorus','1_prechorus'),('Chorus','2_chorus'),('Bridge','4_bridge'),('Outro material','6_outro')]:parts.append(f'<section><b>{role}</b>'+player(f'followup/{name}.wav')+'</section>')
parts.append('<h2>B. Section transitions</h2><p>Short overlap at inferred bar boundaries. These are beat/bar hypotheses; syncopated material produced ambiguous tempo estimates.</p>')
rows=json.loads((O/'validated_transitions.json').read_text())
for row in rows:
 if not row['name'].endswith('_short'):continue
 parts.append(f'<section><b>{row["from_section"].title()} → {row["to_section"].title()}</b><br><small>Landing {row["actual_transition_seconds"]:.2f}s; overlap {row["overlap_seconds"]:.3f}s; estimated pulse {row["outgoing_grid"]["bpm"]:.1f} → {row["incoming_grid"]["bpm"]:.1f} BPM. Local 2s chroma proxy {row.get("local_chroma_cosine_2s",0):.3f}; this does not certify harmony. True downbeat not human-verified.</small>'+player(row['name']+'.wav')+'</section>')
parts.append('<details><summary>Compare hard cuts and longer overlaps</summary>')
for row in rows:
 if not row['name'].endswith('_short'):parts.append('<section>'+html.escape(row['name'])+player(row['name']+'.wav')+'</section>')
parts.append('</details><h2>C. Long-form candidates</h2><section><b>Chained generated sections + existing resolving cadence</b><p>Verse → prechorus → chorus → verse → bridge → chorus → outro. No route labels configured this research assembly.</p>'+player('chained_songform_resolved.wav')+'</section><section><b>Shared-rhythm arrangement comparison</b><p>Approximate harmonic/percussive separation of Chestnut-generated material, with explicit orchestration changes and level-matched sections. This is not true instrument-stem separation and does not prove new harmonic composition.</p>'+player('shared_rhythm_songform.wav')+'</section>')
parts.append('<h2>D. Road-driven form in the normal UI</h2><p>The exact native-generated score is replayed with its archived section decisions. The preparatory section starts 5.15 seconds before the matched steering-onset proxy. This review playback requires no Chestnut. The capture uses observed video-frame and audio-sample timestamps.</p>'+player('../normal_1789528182/synchronized.mp4',True))
parts.append('<details><summary>Community route: final queued-preparation regression</summary><p>The final fresh score, replayed with Chestnut unavailable. This 41-second excerpt includes a preparatory section and bridge landing after the callback-boundary fix.</p><video controls preload="none" src="../normal_1789530685/synchronized.mp4"></video></details>')
for style,title in [('nightshift','E. Synthwave — secondary'),('brassline','F. Funk — experimental')]:
 parts.append('<h2>'+title+'</h2>')
 for file in sorted((O/'styles').glob(style+'_*.wav')):parts.append('<section>'+html.escape(file.stem.split('_',1)[1].title())+player('styles/'+file.name)+'</section>')
parts.append('<h2>G. Arrival / outro</h2><p>Final heard PCM from the arrival-route native regression. The runtime used delivered navigation and standstill, then the existing source-derived cadence.</p>'+player('native_arrival_outro.wav'))
parts.append('<h2>H. Integration evidence</h2><table><tr><th>Run</th><th>Evidence</th></tr><tr><td>Full community / Mac</td><td>571.8 s; zero host starvation, late samples, sequence gaps, output flags, renderer underruns or emergency repeats. Maximum host timing error 0.606 ms.</td></tr><tr><td>Native curve route</td><td>176.3 s; zero underruns/repeats; actual normal UI retained; prechorus 5.15 s before steering proxy.</td></tr><tr><td>Native arrival route</td><td>254.3 s; natural route end; zero underruns/repeats; outro, cadence and silence.</td></tr><tr><td>Stored replay</td><td>Exact contiguous archived samples; no generation; host/comma ownership preserved.</td></tr></table>')
summary=O/'final_metrics.json'
if summary.exists():parts.append('<p><b>Final regression:</b> '+html.escape(json.loads(summary.read_text()).get('headline','See STATUS.md'))+'</p>')
parts.append('<h2>I. Startup</h2><p>Supported normal worker: 127 s in earlier process-cold tests, 185 s in the final resident preparation (197 s before removing repeated safety-monitor imports). Earlier full launcher starts were 145–146 s. Resident-worker launches measured 15.0–16.5 s; see final regression for the latest measurement. The redundant second full generation was removed. Graph snapshots reached 46.6 s but failed trained-output equivalence and are rejected. The 30–45 s cold target remains unmet; no post-boot cold-start claim, lower-bound claim or physical speaker check is made.</p><details><summary>Research controls and limitations</summary><p>Strong anchors constrained variation; short anchors increased contrast but did not guarantee identifiable roles. Text-only generation changes more, with weaker continuity. True downbeats, harmonic coherence and audible macro-form need human evaluation. Snapshot-derived invalid outputs remain quarantined and are not linked as candidates.</p>')
for role in ['verse','chorus','bridge']:parts.append('<section>Text-only control: '+role+player('fresh/'+role+'.wav')+'</section>')
parts.append('<p><a href="../../OVERNIGHT.md">Detailed experiment notes</a> · <a href="../../STATUS.md">Current status</a></p></details></body></html>');(O/'index.html').write_text('\n'.join(parts))
