"""Explicit saved music staging against a separately verified replay recording."""
import hashlib
import json
from pathlib import Path

import numpy as np
import soundfile as sf

from demo_catalog import entry


def digest(path):
  with Path(path).open('rb') as stream:
    return hashlib.file_digest(stream, 'sha256').hexdigest()


def load_staged_music(path, route, launch, load_reference):
  manifest = json.loads((path/'staged_music.json').read_text())
  if (manifest.get('version') != 1 or manifest.get('kind') != 'standalone-music-over-replay'
      or launch.get('route') != route or manifest.get('route') != route
      or launch.get('mode') != 'staged-demo' or launch.get('generation_invoked') is not False):
    raise ValueError('Invalid explicit staged music manifest')
  selected = entry(Path(__file__).resolve().parents[1], manifest.get('reference_alias'))
  reference = Path(selected['archive'])
  reference_launch = json.loads((reference/'launch.json').read_text())
  if reference.resolve() == path.resolve() or reference_launch.get('render_mode') != 'gold-core':
    raise ValueError('Staged music requires an original route recording as timing reference')
  if launch.get('native_replay_args') != reference_launch.get('native_replay_args'):
    raise ValueError('Staged music must preserve the reference replay recipe')
  hashes = manifest.get('reference_hashes', {})
  for name in ('launch.json', 'replay_origin.json', 'audio_blocks.jsonl', 'bridge.json', 'dry.wav'):
    if hashes.get(name) != digest(reference/name):
      raise ValueError('Staged music replay reference changed: '+name)
  reference_audio, rate, meta = load_reference(reference, route)
  expected_frames = len(reference_audio)
  del reference_audio
  for name in ('dry.wav', 'rhythm_timeline.json', 'provenance.json'):
    if manifest.get('asset_hashes', {}).get(name) != digest(path/name):
      raise ValueError('Staged music asset changed: '+name)
  audio, music_rate = sf.read(path/'dry.wav', dtype='float32', always_2d=True)
  if (music_rate != rate or audio.shape != (expected_frames, 2)
      or not np.isfinite(audio).all() or np.max(np.abs(audio)) > 1.):
    raise ValueError('Staged music must match the complete replay duration and output format')
  # The reference supplies only replay timing. The replacement music has its
  # own explicit provenance and is never described as generated by this route.
  return audio, rate, {**meta, 'render_mode':'staged-demo-music', 'mode':'staged-demo',
                       'generation_invoked':False, 'timing_mode':'staged-to-verified-route-recording',
                       'music_provenance':manifest}
