"""Concise private listening review; diagnostic and live recordings are clearly separated."""
import json,html
from pathlib import Path
R=Path(__file__).resolve().parents[1];O=R/'results/unattended'
def read(name,default):
 p=O/name;return json.loads(p.read_text()) if p.exists() else default
def audio(path):return f'<audio controls preload="none" src="{html.escape(path)}"></audio>'
def card(title,description,path):return f'<article><h3>{html.escape(title)}</h3><p>{html.escape(description)}</p>{audio(path)}</article>'
parts=['''<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>RoadScore · unattended review</title><style>body{background:#10151c;color:#edf1f5;font:16px/1.55 system-ui;max-width:1080px;margin:auto;padding:32px 22px}h1{font-size:38px;letter-spacing:-1px}h2{margin-top:48px;border-top:1px solid #34404f;padding-top:22px}h3{margin:0 0 8px}p{color:#bfc9d5}article{background:#19222d;padding:20px;border-radius:12px;margin:14px 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:14px}.grid article{margin:0}audio,video{width:100%;margin-top:10px}a{color:#8dccff}summary{cursor:pointer;padding:14px 0;color:#9dd8ff}table{border-collapse:collapse;width:100%;font-size:13px}td,th{text-align:right;padding:9px;border-bottom:1px solid #34404f}td:first-child,th:first-child{text-align:left}.scroll{overflow:auto}code,pre{background:#202b38;padding:5px;border-radius:4px}pre{white-space:pre-wrap;padding:18px}.late{color:#ffad99}.good{color:#9ce1b1}.tag{color:#9ce1b1;font-size:13px;text-transform:uppercase;letter-spacing:1px}footer{margin:45px 0;color:#adb8c7}</style><header><p class="tag">Private local prototype · bench speaker muted</p><h1>More musical space. Earlier road response. Normal replay.</h1><p>These are candidates for your ears, not a claim that numerical scores establish musical quality. Six genre probes, controlled continuation comparisons, and actual live Chestnut replay captures are kept distinct.</p></header><h2>A · Genre candidates</h2><p>Each is a fresh 30.09-second SA3 generation with the same seed. Prompts request no vocals; human listening must confirm the result. Pulse estimates can lock onto subdivisions and do not certify requested tempo.</p><div class="grid">''']
for r in read('genre_screen.json',[]):
 key=r['identity'];d=r['density'];parts.append(card(r['name'],f"{r['seconds']:.2f}s generation · {r['rtf']:.2f} RTF · pulse proxy {d['pulse']['bpm']:.0f} BPM",f'{key}_seed.wav'))
parts.append('</div><h2>B · Long-form development</h2>')
parts.append(card('Contrasting arrangement · fixed identity anchor','2:58 controlled generation experiment. Bridge, development, build, peak and release prompts with previous context and a fixed identity anchor. No measured near-silence gaps; musical development remains restrained.','ignition_arc_fixed/long.wav'))
parts.append('<details><summary>Rejected tradeoff: more variety, but silence at joins</summary>'+card('No end anchor · not suitable as the current default','Same prompts and seeds; much greater harmonic/timbral change but18.3s below−50dB across the performance. Kept as evidence, not a passing candidate.','ignition_arc_fixed_anchor0/long.wav')+'</details>')
if (O/'native_final/heard.wav').exists():parts.append(card('Live Chestnut + normal onroad · three minutes','Actual captured output during native replay. Fixed anchor retained for this demo, new section prompts, earlier electronic gesture, and the experimental0.6 curve threshold. That threshold is not the recommended default: it regressed a later sharp turn;0.8 is restored. Six new live generations; zero underruns or emergency repeats in this final capture.','native_final/heard.wav'))
else:parts.append(card('Live Chestnut + normal onroad · three minutes','Actual captured output during native replay with six new GPU generations. This earlier run preceded the encode-index camera correction.','native_ignition/heard.wav'))
parts.append('<details><summary>Other continuation families and anchor controls</summary>')
for key,label in [('nightshift_fixed','Synthwave continuation · 100s'),('brassline_fixed','Funk continuation · 100s'),('ignition_fixed','Initial electronic prompts · fixed anchor'),('ignition_moving','Initial electronic prompts · refreshed anchor'),('ignition_arc_fixed_anchor22','Two-second anchor · promising126s comparison')]:parts.append(card(label,'Controlled route-free generation experiment.',key+'/long.wav'))
parts.append('</details><h2>C · Curve</h2>')
if (O/'curve_synchronized.mp4').exists():parts.append('<p>Original route camera footage synchronized to the final captured performance using measured host/bench clock offset and model delivery times. This review video is camera footage, not a screen recording of the normal UI. The actual normal UI camera/path/lane execution is separately instrumented below.</p><video controls preload="metadata" src="curve_synchronized.mp4"></video>')
parts.append('<details><summary>Style-aware curve comparisons · same captured causal event states</summary><p>Offline diagnostic renders using generated source material. The event stream is identical; these are not additional live-driving tests. The electronic version clears bass and adds subdivisions; synthwave adds stereo answers; funk emphasizes existing attacks.</p>')
for key in ['ignition','nightshift','brassline']:parts.append(card(key.title()+' · new style gesture','Compare preparation before the curve; do not judge only the peak.',f'{key}_curve_style.wav')+card(key.title()+' · previous shared effect','Same source and event states.',f'{key}_curve_previous.wav'))
parts.append('</details><h2>D · Arrival</h2><p>The previously liked cadence remains available unchanged. The new electronic arrival tests the same vehicle trigger and phrase-runway mechanism with different source music.</p>')
parts.append(card('Preserved Horizon arrival','Previously reviewed version; resolving cadence with2.923s runway.','../dense/live_arrival/heard.wav'))
if (O/'arrival_synchronized.mp4').exists():parts.append('<video controls preload="metadata" src="arrival_synchronized.mp4"></video>')
else:parts.append(card('New electronic arrival · live normal replay','Final regression of the same vehicle trigger and source-dependent phrase runway. No fade-to-silence replacement.','native_final_arrival/heard.wav'))
parts.append('<h2>E · End-to-end timing</h2><p>Times below are seconds within each route. Physical labels are steering proxies, not measured geometric curvature or visually adjudicated entry. Onset follows300ms below3° relative to neutral steering; peak is maximum steering excursion. Slow sharp turns can begin steering before the model/speed gate qualifies. Negative lead means late.</p><p>Audio proxies compare the same generated source through neutral versus event processing:10% or20% residual RMS sustained300ms, with a minimum source level. They measure signal change, not human audibility. The old6.2-second claim described early control/output, not a strong musical response.</p>')
labels=read('curve_timing.json',{}).get('events',[])
parts.append('<div class="scroll"><table><tr><th>Route / curve</th><th>First prediction</th><th>Activation</th><th>Command</th><th>1% audio</th><th>10% audio</th><th>20% audio</th><th>Steering onset</th><th>Steering peak</th><th>20% lead</th></tr>')
seen=set()
def val(v):return '—' if v is None else f'{v:.2f}'
for r in labels:
 if not r['capture'] or r['ambiguous_onset'] or r['activation'] in seen:continue
 seen.add(r['activation']);lead=r['leads']['strong_proxy'];parts.append('<tr><td>'+r['route'][:8]+' / '+r['class']+'</td>'+''.join('<td>'+val(r[k])+'</td>' for k in ['predicted_detection','activation','command','measurable','meaningful_proxy','strong_proxy','steering_onset','steering_peak'])+f'<td class="{"late" if lead is not None and lead<0 else "good"}">{val(lead)}</td></tr>')
parts.append('</table></div><p>This table is the original captured baseline. <a href="curve_timing.json">Full labels and definitions</a> · <a href="threshold_sensitivity.json">Whole-route threshold study</a> · <a href="enhanced_response_summary.json">Same-source earlier rock gesture comparison</a>.</p>')
p=O/'native_final/synchronized_timing.json'
if p.exists():
 new=json.loads(p.read_text());parts.append(f'<h3>Final synchronized electronic run</h3><p>Initial LAN clock estimate ±{new["output_uncertainty_seconds"]*1000:.1f}ms; median bridge transit{new["network_delay_median_seconds"]*1000:.1f}ms. PortAudio DAC timestamps remain software estimates; see the timing JSON for drift checks and limitations.</p><div class="scroll"><table><tr><th>Activation</th><th>Qualification began</th><th>Command</th><th>First output</th><th>10% response</th><th>20% response</th></tr>')
 for e in new['events']:parts.append('<tr>'+''.join('<td>'+val(e.get(k))+'</td>' for k in ['activation','qualified_since','command_source_t','first_output','proxy10','proxy20'])+'</tr>')
 parts.append('</table></div><p><a href="native_final/synchronized_timing.json">Complete synchronized measurement</a>. Slow sharp turns remain a limitation. The0.6 trial can delay later events and was not adopted; the bench default is0.8.</p>')
parts.append('<h3>Final cross-route outcomes</h3><p>Each stage has a lead-to-steering value in the full JSON. Unmatched events have no distinct steering peak under the fixed labeling rule; they are not counted as successes. Negative lead means the strong response was late.</p><div class="scroll"><table><tr><th>Route</th><th>Activation</th><th>Steering onset</th><th>20% response</th><th>20% lead</th></tr>')
for e in read('final_timing_table.json',{}).get('events',[]):
 lead=e['lead_to_steering']['proxy20'];parts.append('<tr><td>'+e['route'][:8]+'</td><td>'+val(e['activation'])+'</td><td>'+val(e['steering_onset'])+'</td><td>'+val(e['proxy20'])+'</td><td class="'+('late' if lead is not None and lead<0 else 'good')+'">'+val(lead)+'</td></tr>')
parts.append('</table></div><p><a href="final_timing_table.json">Complete chain and per-stage leads for both final routes</a>.</p>')
parts.append('''<h2>F · Normal replay status</h2><pre>cd ~/Desktop/RoadScore
./onroad --routeid 'DONGLE_ID/ROUTE_ID' --roadscore</pre><p>Uses the existing native replay and existing openpilot UI, with its real camera/path/lane/speed presentation. Cached route folders are discovered by identity; an uncached ID goes to the native route resolver. No 201/202/203 allowlist, no musical timestamps, no rerun of modeld. Three cached routes have been exercised; an unseen community route and its access permissions remain an unperformed acceptance test.</p><p>The prepared bench must be reachable. A cold run starts its own worker, waits roughly 2–3 minutes for preparation, and restores CPU settings when finished. The cold-start ownership/cleanup path was exercised. Output is muted and captured. Add <code>--audible</code> only when you want the bench speaker enabled; this was not exercised during the unattended session. The default run lasts180s; use <code>--duration</code> and optional <code>--start</code>. Pause/seek/rate changes are not supported by this music adapter; restart for a new clock.</p><p>Live and replay share the same RoadScore app, detector, DSP, arrival and generation scheduler. The source/clock adapter changes; live modeld coexistence is still untested. The shared live adapter is code-tested, not road-validated.</p><footer>No route media or location data was uploaded. Public StarPilot remains untouched. These files are private local artifacts. See <a href="../../UNATTENDED.md">development report</a> and <a href="../../STATUS.md">current status</a>.</footer>''')
(O/'listen.html').write_text(''.join(parts));print(O/'listen.html')
