"""Exact development-only Torque platform cohorts."""

TOYOTA_VEHICLES = frozenset({
  'TOYOTA_ALPHARD_TSS2', 'TOYOTA_AVALON', 'TOYOTA_AVALON_2019', 'TOYOTA_AVALON_TSS2',
  'TOYOTA_CAMRY', 'TOYOTA_CAMRY_TSS2', 'TOYOTA_CHR', 'TOYOTA_CHR_TSS2',
  'TOYOTA_COROLLA', 'TOYOTA_COROLLA_TSS2', 'TOYOTA_HIGHLANDER', 'TOYOTA_HIGHLANDER_TSS2',
  'TOYOTA_PRIUS', 'TOYOTA_PRIUS_V', 'TOYOTA_PRIUS_TSS2', 'TOYOTA_RAV4', 'TOYOTA_RAV4H',
  'TOYOTA_RAV4_TSS2', 'TOYOTA_RAV4_TSS2_2022', 'TOYOTA_RAV4_PRIME', 'TOYOTA_YARIS',
  'TOYOTA_MIRAI', 'TOYOTA_SIENNA', 'TOYOTA_SIENNA_4TH_GEN', 'LEXUS_CTH', 'LEXUS_ES',
  'LEXUS_ES_TSS2', 'LEXUS_IS', 'LEXUS_IS_TSS2', 'LEXUS_NX', 'LEXUS_NX_TSS2',
  'LEXUS_LC_TSS2', 'LEXUS_RC', 'LEXUS_RC_TSS2', 'LEXUS_RX', 'LEXUS_RX_TSS2',
  'LEXUS_GS_F', 'LEXUS_LS',
})

IONIQ6_VEHICLES = frozenset({'HYUNDAI_IONIQ_6'})
BOLT_VEHICLES = frozenset({
  'CHEVROLET_BOLT_CC_2017', 'CHEVROLET_BOLT_CC_2018_2021', 'CHEVROLET_BOLT_CC_2022_2023',
  'CHEVROLET_BOLT_ACC_2022_2023', 'CHEVROLET_BOLT_ACC_2022_2023_PEDAL',
})
GM_VEHICLES = frozenset({
  'BUICK_BABYENCLAVE',
  'BUICK_LACROSSE_ASCM',
  'BUICK_LACROSSE_ASCM_19US',
  'CADILLAC_CT6_CC',
  'CADILLAC_ESCALADE_ASCM',
  'CADILLAC_ESCALADE_ESV_2019_ASCM',
  'CADILLAC_XT4',
  'CADILLAC_XT4_CC',
  'CADILLAC_XT5',
  'CADILLAC_XT5_CC',
  'CADILLAC_XT6',
  'CHEVROLET_BLAZER',
  'CHEVROLET_BOLT_ACC_2022_2023',
  'CHEVROLET_BOLT_ACC_2022_2023_PEDAL',
  'CHEVROLET_BOLT_CC_2017',
  'CHEVROLET_BOLT_CC_2018_2021',
  'CHEVROLET_BOLT_CC_2022_2023',
  'CHEVROLET_EQUINOX',
  'CHEVROLET_EQUINOX_CC',
  'CHEVROLET_MALIBU_ASCM',
  'CHEVROLET_MALIBU_CC',
  'CHEVROLET_MALIBU_HYBRID_CC',
  'CHEVROLET_MALIBU_SDGM',
  'CHEVROLET_SILVERADO',
  'CHEVROLET_SILVERADO_CC',
  'CHEVROLET_SUBURBAN',
  'CHEVROLET_SUBURBAN_ASCM',
  'CHEVROLET_SUBURBAN_CAMERA',
  'CHEVROLET_SUBURBAN_CC',
  'CHEVROLET_TRAILBLAZER',
  'CHEVROLET_TRAILBLAZER_CC',
  'CHEVROLET_TRAVERSE',
  'CHEVROLET_TRAX',
  'CHEVROLET_VOLT',
  'CHEVROLET_VOLT_2019',
  'CHEVROLET_VOLT_ASCM',
  'CHEVROLET_VOLT_CAMERA',
  'CHEVROLET_VOLT_CC',
  'GMC_YUKON',
  'GMC_YUKON_CC',
})
GAIN_VEHICLES = GM_VEHICLES
SUPPORTED_VEHICLES = TOYOTA_VEHICLES | IONIQ6_VEHICLES | GM_VEHICLES
